language: java
env:
  global:
  - export PATH="/opt/rakudo-pkg/bin:/opt/rakudo-pkg/share/perl6/site/bin:$PATH"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
addons:
  apt:
    sources:
    - sourceline: deb https://dl.bintray.com/nxadm/rakudo-pkg-debs $(lsb_release -cs)
        main
      key_url: http://keyserver.ubuntu.com/pks/lookup?search=0x379CE192D401AB61&op=get
    packages:
    - rakudo-pkg
before_script:
- (cd perl6-idea-plugin/ && ./gradlew assemble")
script:
- (cd tools/p6-grammar-to-idea/ && prove --jobs=1 -e "perl6-m -Ilib")
- (cd perl6-idea-plugin/ && ./gradlew test")
after_success:
- (cd perl6-idea-plugin/ && ./gradlew buildPlugin")
deploy:
  provider: s3
  access_key_id: AKIAJV46PZNKKRZTY3EQ
  secret_access_key:
    secure: dgHgQvaflj/BCM1aDum6uPNQu4niXxLJTO3E/kT+NAWe4ra4c2DbdVm9ZwkCyJxoovWwvOxJpvRTzkTvZyeA7f2NEl4BHsbQ3zGsgYk3K7CqVnEmzqGv79syzuEcdmbMepQcLEqHscb2KCxnJgZ6Bb7MAMBEPLPJx/hlVqhci2aHZwUNjupTvMdZykFYXvmKMBprRaDfhsjkTnWURyO0raID/8wPOTGFJ/TxIVLBpXWxxndv/NsV4jg/PU/73WxyhLmtlpyJn4ozeHCAL55wgmACCpPzwlsyxfFHgNXMqMLJ58f6oAKXjgTLfr7GkTsWCqKEMhWR0H4CTGBPD2S2oadzw0l1lLkWhpK1YfvoBepQdpqad4HOKM/sWwX1aHZm2SVeGiExpckBkhGDuen2+JY1DouY97ixcWIK/3SqXAmrsNLiavvNca1L4J+2PgADdeAXnM5lsfgqafpivGDIvUurx6FRv53mnQel9P1mh8vxK2OO2HF2ZAv/IoyGqZNW4jZFKnMfgXeOkboTD3Jkd46uxEv/3UrOWH/QZpD3DGFjMK3/RNjy0ikTiK3MmgwjaINdXA7/F4Yo0kBc55l0cTbVQshZkclbkcz3b5cBc9r9gMYtoCGgGTyWNZoa/D9WCr1F4SJU26goAP2Nw0SKZdbozbMMULPFRmpmVazvK2c=
  bucket: comma-plugin
  skip_cleanup: true
  local-dir: build/distributions
  on:
    repo: edumentab/perl6-idea-plugin
    branch: master
notifications:
  slack:
    secure: h96D7ADnEYeD5/Ro8Y5HY9ZhmC84X2KOK1tOSvBpIJhte2MDquPKZO2r4J1hEHTMXHGMGtGr1dWtdvgcE6mKCik3ns7F22xzWFjhNl2XqWrGWZvkTZVuJNZEOfHeNw3aFdrA3vr8tGIPiNVIKCP0GOgbTocJlvsMGhhqm6GqHsZI6OQiOfmd41+Y0rNKZ0J948vxWrKtb3SSyrUqz9eRaCirzSV+ITozpUYmrDgDO9X28bgiEy4DJsxDFc+3btIuIhtzRglyGcguKZ+w0ovoNDCBPk6MRiyw71o7ddRlkOVQ400cT6x5b2jh0mCogmrXKZErvVClQRUZAEhkEGZpPUFhiL0By80jSpGXSmoX6F8xGpNiuc/8mLx4sdRHalKSiN4dzeaPF9Dvvi81RY5gFWubJAVde4pJymRzJhYiHPnAPqWB+PyQgmCRet8+9cAL365D2iDtuOGjvOAMtCXE9WqETFo2Md8srSfU4vdMz7LiYGDJytYNbJITjW+08szVzR1rXClxAN54hHBqDBsTNy3Wby/41WmpSRoS4cVaoUzrWWhr6nJSEIIktsYpKU/qbJW1eDVLPZbCOs1L8Wxudroyrf2ZqKgeENVBkwGgjVEvXlpe/bTx8sQwJ3M4TyPrm/SJU9PeEed++0N48p9w2ae44snScN9BjtA4EbRdaRI=
