language: java
dist: trusty
before_install:
- git clone --progress --depth 1 -b comma-201 git@github.com:edumentab/intellij-community.git
- mkdir intellij-community/comma-build
- shopt -s extglob
- mv !(intellij-community) intellij-community/comma-build/
env:
  global:
  - export PATH="/opt/rakudo-pkg/bin:/opt/rakudo-pkg/share/perl6/site/bin:$PATH"
addons:
  apt:
    sources:
    - sourceline: deb https://dl.bintray.com/nxadm/rakudo-pkg-debs $(lsb_release -cs)
        main
      key_url: http://keyserver.ubuntu.com/pks/lookup?search=0x379CE192D401AB61&op=get
    packages:
    - rakudo-pkg
script:
- zef install OO::Monitors JSON::Fast
- (cd intellij-community/comma-build/perl6-idea-plugin/tools/p6-grammar-to-idea/ && prove --jobs=1 -e "perl6-m -Ilib")
- (cd intellij-community/comma-build/perl6-idea-plugin/tools/symbol-script-module && zef install .)
- (cd intellij-community/comma-build/perl6-idea-plugin/tools/symbol-script-module && perl6 symbol-script-test.p6)
- (cd intellij-community/comma-build/perl6-idea-plugin/tools/symbol-script-module && perl6 test-harness-test.p6)
- (cd intellij-community/comma-build && ant test)
notifications:
  slack:
    secure: h96D7ADnEYeD5/Ro8Y5HY9ZhmC84X2KOK1tOSvBpIJhte2MDquPKZO2r4J1hEHTMXHGMGtGr1dWtdvgcE6mKCik3ns7F22xzWFjhNl2XqWrGWZvkTZVuJNZEOfHeNw3aFdrA3vr8tGIPiNVIKCP0GOgbTocJlvsMGhhqm6GqHsZI6OQiOfmd41+Y0rNKZ0J948vxWrKtb3SSyrUqz9eRaCirzSV+ITozpUYmrDgDO9X28bgiEy4DJsxDFc+3btIuIhtzRglyGcguKZ+w0ovoNDCBPk6MRiyw71o7ddRlkOVQ400cT6x5b2jh0mCogmrXKZErvVClQRUZAEhkEGZpPUFhiL0By80jSpGXSmoX6F8xGpNiuc/8mLx4sdRHalKSiN4dzeaPF9Dvvi81RY5gFWubJAVde4pJymRzJhYiHPnAPqWB+PyQgmCRet8+9cAL365D2iDtuOGjvOAMtCXE9WqETFo2Md8srSfU4vdMz7LiYGDJytYNbJITjW+08szVzR1rXClxAN54hHBqDBsTNy3Wby/41WmpSRoS4cVaoUzrWWhr6nJSEIIktsYpKU/qbJW1eDVLPZbCOs1L8Wxudroyrf2ZqKgeENVBkwGgjVEvXlpe/bTx8sQwJ3M4TyPrm/SJU9PeEed++0N48p9w2ae44snScN9BjtA4EbRdaRI=
