language: java

env:
  global:
    - export PATH="/opt/rakudo-pkg/bin:/opt/rakudo-pkg/share/perl6/site/bin:$PATH"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/nxadm/rakudo-pkg-debs $(lsb_release -cs) main'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?search=0x379CE192D401AB61&op=get'
    packages:
      - rakudo-pkg

before_script:
  - ./gradlew assemble

script:
  # Test p6-grammer-to-idea/
  - (cd tools/p6-grammar-to-idea/ && prove --jobs=1 -e "perl6-m -Ilib")
  # Run unit tests
  - ./gradlew test

after_success:
  - ./gradlew buildPlugin

deploy:
  provider: s3
  access_key_id: AKIAJV46PZNKKRZTY3EQ
  secret_access_key:
    secure: dgHgQvaflj/BCM1aDum6uPNQu4niXxLJTO3E/kT+NAWe4ra4c2DbdVm9ZwkCyJxoovWwvOxJpvRTzkTvZyeA7f2NEl4BHsbQ3zGsgYk3K7CqVnEmzqGv79syzuEcdmbMepQcLEqHscb2KCxnJgZ6Bb7MAMBEPLPJx/hlVqhci2aHZwUNjupTvMdZykFYXvmKMBprRaDfhsjkTnWURyO0raID/8wPOTGFJ/TxIVLBpXWxxndv/NsV4jg/PU/73WxyhLmtlpyJn4ozeHCAL55wgmACCpPzwlsyxfFHgNXMqMLJ58f6oAKXjgTLfr7GkTsWCqKEMhWR0H4CTGBPD2S2oadzw0l1lLkWhpK1YfvoBepQdpqad4HOKM/sWwX1aHZm2SVeGiExpckBkhGDuen2+JY1DouY97ixcWIK/3SqXAmrsNLiavvNca1L4J+2PgADdeAXnM5lsfgqafpivGDIvUurx6FRv53mnQel9P1mh8vxK2OO2HF2ZAv/IoyGqZNW4jZFKnMfgXeOkboTD3Jkd46uxEv/3UrOWH/QZpD3DGFjMK3/RNjy0ikTiK3MmgwjaINdXA7/F4Yo0kBc55l0cTbVQshZkclbkcz3b5cBc9r9gMYtoCGgGTyWNZoa/D9WCr1F4SJU26goAP2Nw0SKZdbozbMMULPFRmpmVazvK2c=
  bucket: comma-plugin
  skip_cleanup: true
  local-dir: build/distributions
  on:
    repo: edumentab/perl6-idea-plugin
    branch: master
notifications:
  slack:
    secure: FWTmN59qyqPcxE+efPdP4uqr93E1XjEd5+QbZA2H8Gj2r+4vk04wW+A9HOXYqBb1Sh3ct+LDCNtBTYn6P5wRJDsPaZmA3vX9W36KP/AQ81cuJAgE1PUg7+/IRckyyybZDxMocuB9cV4Q2ZxhQPSd0HW0fhdzaGJfoDeduMKEM+mZHXasiFti7dLt7nvIgf1AoLuKKOuzrZIrv228+nJn63ZJZzS7ULehC6SE0LrncwQNLWkiSJj9D5egosdMipbEnprlCMZWQG844MpZ1xwEycZPGNrpScQ2hlZcvfSgotEAj+amiL3xaCUAXUtro+nABqvGGsuKsCcWzrx/rril3tiL/l3m9tUII7HgMZHIQcJMhbtW+437gs66TU7AIwJCdBerUe7qcNwzD7GOUfZP/ZeGH4jff7hHM+qDtuenn9tGFL50E//KdcARtSajawIsXWY/vBN5Nrzqp0pl7xC3s0+dCmz+Fx/7EdslVFf/I1Ivl7rDECOioKDi7ShvTNvg8N5186c874pgI3vo6jUHOU9cxwm1+avJnpwQNKyJuR1pruqf1xSG+DdoDmmnB+sNFcPCpsuq3u9zJaa4GYOFUMO4TW5tNKXARYyyiVf4WoMQKVsQ1K3Skk3BNVhIY0fQFXVnVoFtjcNMQzBYXYImH2oTucTmToCusz7aMHoSA0c=
